name: CI

on: push

env:
  GIT_USER: iziyang
  GIT_EMAIL: iyuanzz@qq.com
  THEME_REPO: theme-next/hexo-theme-next
  THEME_BRANCH: master
  DEPLOY_REPO: iziyang/iziyangtest.github.io
  DEPLOY_BRANCH: master
  THEME_PATH: themes/next

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout theme repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.THEME_REPO }}
          ref: ${{ env.THEME_BRANCH }}
          path: ${{ env.THEME_PATH }}


      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
          
      - name: Setup Hexo Dependencies
        run: |
          npm install hexo-cli -g
          npm install
          npm install hexo-deployer-git --save

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          cp _config.theme.yml themes/next/_config.yml

      - name: Deploy Hexo 
        run: |
          hexo clean
          hexo generate 
          hexo deploy
